language: go
go:
  #- 1.9.x
  #- 1.10.x
  #- 1.11.x
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - sudo apt-get install -y zip unzip
  - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
  - unzip terraform_0.12.7_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
  - mkdir custom && cp -r conf custom
  - chmod +x start.sh
  - export AWS_ACCESS_KEY_ID=$access_key_id
  - export AWS_SECRET_ACCESS_KEY="$secret_access_key"
 # - export TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - sed -i 's/TNUMBER/'"$TRAVIS_BUILD_NUMBER"'/g' gogs.tf
  - terraform init
  - terraform plan
  - terraform apply -auto-approve
  
  #- sed -i "s/DOMAIN = APP_ENV_IP/DOMAIN =  $ip_env/" app.ini
 # - sed -i "s/HOST = 127.0.0.1:3306/HOST = $db_ip:3306/" app.ini
 # - sed -i "s/PASSWD = passwd/PASSWD = $db_passwd/" app.ini
  - zip -r eb.zip gogs public scripts templates LICENSE README_ZH.md README.md custom Buildfile start.sh #app.ini #Procfile .ebextensions

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"  
  app: "gogstf-$TRAVIS_BUILD_NUMBER"
  env: "gogsenvtf-$TRAVIS_BUILD_NUMBER"
  bucket_name: "elasticbeanstalk-gogs"
  zip_file: eb.zip
  on:
    branch: master
