language: go
go:
  #- 1.9.x
  #- 1.10.x
  #- 1.11.x
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - sudo apt-get install -y zip unzip
  - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
  - unzip terraform_0.12.7_linux_amd64.zip
#   - wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
#   - unzip terraform_0.11.14_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version

script:
 # - go build -v -tags "pam"
 # - go test -v -cover -race ./...
#   - sed -i 's/RUN_MODE = dev/RUN_MODE = prod/g' conf/app.ini
#   - sed -i 's+ROOT =+ROOT = /home/gogs/gogs-repositories+g' conf/app.ini
#   - sed -i 's+127.0.0.1:3306+'"$gogs_db_host"':3306+g' conf/app.ini
#   - sed -i 's/USER = root/USER = gogs/g' conf/app.ini
#   - sed -i '171 s/PASSWD =/PASSWD = '"$gogs_db_pass"'/g' conf/app.ini  # 171str
#   - sed -i 's/INSTALL_LOCK = false/INSTALL_LOCK = true/g' conf/app.ini
#   - sed -i '324 s+ROOT_PATH =+ROOT_PATH = /home/gogs/log+g' conf/app.ini  #324str

  - mkdir custom && cp -r conf custom
  - chmod +x start.sh
  - export AWS_ACCESS_KEY_ID=$access_key_id
  - export AWS_SECRET_ACCESS_KEY="$secret_access_key"
  - export AWS_ACCESS_KEY_ID_B=$(echo $access_key_id | base64)
  - export AWS_SECRET_ACCESS_KEY_B=$(echo $secret_access_key | base64)
  - echo $AWS_ACCESS_KEY_ID_B and $AWS_SECRET_ACCESS_KEY_B
  - sed -i 's/TNUMBER/'"$TRAVIS_BUILD_NUMBER"'/g' gogs.tf
  
  - sed -i 's/AWS_ACCESS_KEY_ID_B/'"$AWS_ACCESS_KEY_ID_B"'/g' gogs.tf
  - sed -i 's/AWS_SECRET_ACCESS_KEY_B/'"$AWS_SECRET_ACCESS_KEY_B"'/g' gogs.tf
  - touch s3fs-file
  - echo "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY" | base64 > s3fs-file
  - terraform init
  - terraform plan
  - terraform apply -auto-approve
  - zip -r eb.zip gogs public scripts templates LICENSE README_ZH.md README.md custom Buildfile start.sh 

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"  
  app: "gogstf-$TRAVIS_BUILD_NUMBER"
  env: "gogsenvtf-$TRAVIS_BUILD_NUMBER"
  bucket_name: "elasticbeanstalk-gogs"
  zip_file: eb.zip
  on:
    branch: master
    
notifications:
  slack: universebigteam:$slack
