language: go
go:
  #- 1.9.x
  #- 1.10.x
  #- 1.11.x
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - sudo apt-get install -y zip

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
  - ls
  - file gogs
  - file gogs.go
  - hostname -I
  - pwd
  - mkdir gogs_folder
  - cp -r gogs public scripts templates LICENSE README_ZH.md README.md gogs_folder
  - zip -r gogs.zip gogs_folder
  #- cd ..
  #- ls
  #- file gogs
  #- zip -r gogs.zip gogs
 # - ls
  #- file gogs.zip
  #- cd gogs
  
deploy:
  skip_cleanup: true
  file: /home/travis/gopath/src/github.com/nameisalreadytakenexception/gogs/gogs.zip
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"  
  app: "gogs0_0"
  env: "Gogs00-env"
  bucket_name: "elasticbeanstalk-gogs"
  on:
branch: master
#after_deploy:
 # - make -tags "pam"
  #- ./gogs web

#lets go
#commit
