language: go
go:
  #- 1.9.x
  #- 1.10.x
  #- 1.11.x
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - sudo apt-get install -y zip

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
  - ls
  - file gogs
  - pwd
  #- mkdir eb
  #- cp -r gogs public scripts templates LICENSE README_ZH.md README.md eb
  - zip -r eb.zip gogs public scripts templates LICENSE README_ZH.md README.md Procfile
  #- cd eb && ls
  #- cd ..
  #- zip -r eb.zip eb && ls
  #- cd ..
  #- ls
  #- file gogs
  #- zip -r gogs.zip gogs
 # - ls
  #- file gogs.zip
  #- cd gogs
  
deploy:
  skip_cleanup: true
  #file: /home/travis/gopath/src/github.com/nameisalreadytakenexception/gogs/eb.zip
  #file: eb.zip
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"  
  app: "gogs"
  env: "Gogs-env"
  bucket_name: "elasticbeanstalk-gogs"
  #local_dir: eb
  zip_file: eb.zip
  on:
branch: master
#after_deploy:
 # - make -tags "pam"
  #- ./gogs web

#lets go go
