language: go
go:
  #- 1.9.x
  #- 1.10.x
  #- 1.11.x
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
  - ls
  - file gogs
  - hostname -I
  - whoami
  - sudo ufw enable
  - sudo ufw allow 3000
  - ./gogs web
  - curl http:localhost:3000
