language: go
go:
  #- 1.9.x
  #- 1.10.x
  #- 1.11.x
  - 1.12.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam-dev
  - sudo apt-get install -y zip

script:
  - go build -v -tags "pam"
  - go test -v -cover -race ./...
  - mkdir custom
  - cp -r conf custom
  - chmod +x start.sh
  - zip -r eb.zip gogs public scripts templates LICENSE README_ZH.md README.md Procfile custom Buildfile start.sh #.ebextensions

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"
  region: "eu-central-1"  
  app: "gogstf"
  env: "gogsenvtf"
  bucket_name: "elasticbeanstalk-gogs"
  zip_file: eb.zip
  on:
    branch: master
#after_deploy:
 # - make -tags "pam"
  #- ./gogs web

#lets go 
