version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\nameisalreadytakenexception\gogs
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.11

build: false
deploy: false

install:
  - go build -v #-tags "pam"
  - go test -v -cover -race ./...

notifications:
  - provider: Email
    to:
      - dimafriend2008@gmail.com
    on_build_success: true
