image: Visual Studio 2017
version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\nameisalreadytakenexception\gogs
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.11

build: false
deploy: false

install:
  - whoami
  - uname
  - uname -v
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - go build -v #-tags "pam"
  - go test -v -cover -race ./...

notifications:
  - provider: Email
    to:
      - dimafriend2008@gmail.com
    on_build_success: true
